export const styles: { [key: string]: React.CSSProperties } = {
  page: {
    display: "flex",
    minHeight: "100vh",
    fontFamily: "Arial, sans-serif",
  },
  sidebar: {
    width: "40%",
    minWidth: 320,
    backgroundColor: "#5A1418",
    color: "#fff",
    padding: "40px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  logo: {
    fontWeight: "bold",
    fontSize: 14,
  },
  logoSlash: {
    fontWeight: "normal",
    opacity: 0.7,
  },
  headline: {
    fontSize: 34,
    lineHeight: 1.2,
    marginBottom: 16,
  },
  headlineText: {
    fontSize: 14,
    lineHeight: 1.6,
  },
  stats: {
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    marginTop: 24,
  },
  statNumber: {
    fontSize: 22,
    fontWeight: "bold",
    margin: 0,
  },
  statLabel: {
    fontSize: 12,
    opacity: 0.8,
    marginTop: 6,
    marginBottom: 0,
  },
  formSide: {
    flex: 1,
    background: "#f7f7f7",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "40px 20px",
  },
  formBox: {
    width: "100%",
    maxWidth: 620,
    background: "#fff",
    borderRadius: 18,
    padding: "32px 28px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.08)",
  },
  divider: {
    width: 64,
    height: 4,
    background: "#5A1418",
    borderRadius: 4,
    marginBottom: 20,
  },
  title: {
    margin: 0,
    fontSize: 28,
    color: "#1f1f1f",
  },
  subtitle: {
    marginTop: 8,
    color: "#5b5b5b",
    lineHeight: 1.5,
  },
  label: {
    display: "block",
    marginBottom: 8,
    marginTop: 18,
    fontWeight: 600,
    color: "#2a2a2a",
  },
  input: {
    width: "100%",
    height: 46,
    padding: "0 12px",
    borderRadius: 10,
    border: "1px solid #d9d9d9",
    fontSize: 14,
    boxSizing: "border-box",
    outline: "none",
  },
  row: {
    display: "flex",
    gap: 16,
  },
  col: {
    flex: 1,
  },
  toggleSenha: {
    position: "absolute",
    right: 10,
    top: "50%",
    transform: "translateY(-50%)",
    background: "transparent",
    border: "none",
    color: "#5A1418",
    cursor: "pointer",
    fontWeight: 600,
  },
  erro: {
    marginTop: 16,
    color: "#b42318",
    fontWeight: 600,
  },
  botao: {
    width: "100%",
    marginTop: 24,
    border: "none",
    background: "#5A1418",
    color: "#fff",
    borderRadius: 12,
    height: 48,
    fontWeight: 700,
    cursor: "pointer",
  },
};
