import type { Product } from '@/types/products';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'AN-1042',
    photoUrl: null,
    name: 'Vestido Midi Verde',
    code: 'AN-1042',
    piece: 'Vestido',
    style: 'Romântico',
    color: 'Verde',
    sizes: ['P', 'M', 'G'],
    price: 199,
    status: 'PUBLICADO',
  },
  {
    id: 'AN-1039',
    photoUrl: null,
    name: 'Blazer Branco Alfaiataria',
    code: 'AN-1039',
    piece: 'Blazer',
    style: 'Clássico',
    color: 'Off-white',
    sizes: ['P', 'M', 'G', 'GG'],
    price: 459,
    status: 'PUBLICADO',
  },
  {
    id: 'AN-1035',
    photoUrl: null,
    name: 'Camisa Azul Listrada',
    code: 'AN-1035',
    piece: 'Camisa',
    style: 'Casual',
    color: 'Azul',
    sizes: ['P', 'M', 'G'],
    price: 199.9,
    status: 'PUBLICADO',
  },
  {
    id: 'AN-1031',
    photoUrl: null,
    name: 'Calça Alfaiataria Cinza',
    code: 'AN-1031',
    piece: 'Calça',
    style: 'Clássico',
    color: 'Cinza',
    sizes: ['36', '38', '40', '42'],
    price: 289,
    status: 'RASCUNHO',
  },
  {
    id: 'AN-1029',
    photoUrl: null,
    name: 'Casaco Terracota',
    code: 'AN-1029',
    piece: 'Casaco',
    style: 'Criativo',
    color: 'Terracota',
    sizes: ['M', 'G'],
    price: 289,
    status: 'PUBLICADO',
  },
  {
    id: 'AN-1024',
    photoUrl: null,
    name: 'Vestido Longo Preto',
    code: 'AN-1024',
    piece: 'Vestido',
    style: 'Dramático',
    color: 'Preto',
    sizes: ['P', 'M'],
    price: 349,
    status: 'PAUSADO',
  },
  {
    id: 'AN-1019',
    photoUrl: null,
    name: 'Sapatilha Preta',
    code: 'AN-1019',
    piece: 'Sapato',
    style: 'Refinado',
    color: 'Preto',
    sizes: ['35', '36', '37', '38', '39'],
    price: 179,
    status: 'PUBLICADO',
  },
  {
    id: 'AN-1014',
    photoUrl: null,
    name: 'Camiseta Lisa Off-white',
    code: 'AN-1014',
    piece: 'Camiseta',
    style: 'Casual',
    color: 'Off-white',
    sizes: ['P', 'M', 'G'],
    price: 89.9,
    status: 'RASCUNHO',
  },
];
