import type { Produto } from '../../types/produto';

export const MOCK_PRODUTOS: Produto[] = [
  {
    id: 'AN-1842',
    fotoUrl: null,
    nome: 'Vestido Midi Verde',
    codigo: 'AN-1842',
    peca: 'Vestido',
    estilo: 'Romântico',
    cor: 'Verde',
    tamanhos: ['P', 'M', 'G'],
    preco: 199,
    status: 'PUBLICADO',
  },
  {
    id: 'AN-1839',
    fotoUrl: null,
    nome: 'Blazer Branco Alfaiataria',
    codigo: 'AN-1839',
    peca: 'Blazer',
    estilo: 'Clássico',
    cor: 'Off-white',
    tamanhos: ['P', 'M', 'G', 'GG'],
    preco: 459,
    status: 'PUBLICADO',
  },
  {
    id: 'AN-1835',
    fotoUrl: null,
    nome: 'Camisa Azul Listrada',
    codigo: 'AN-1835',
    peca: 'Camisa',
    estilo: 'Casual',
    cor: 'Azul',
    tamanhos: ['P', 'M', 'G'],
    preco: 199.9,
    status: 'PUBLICADO',
  },
  {
    id: 'AN-1831',
    fotoUrl: null,
    nome: 'Calça Alfaiataria Cinza',
    codigo: 'AN-1831',
    peca: 'Calça',
    estilo: 'Clássico',
    cor: 'Cinza',
    tamanhos: ['36', '38', '40', '42'],
    preco: 289,
    status: 'RASCUNHO',
  },
  {
    id: 'AN-1829',
    fotoUrl: null,
    nome: 'Casaco Terracota',
    codigo: 'AN-1829',
    peca: 'Casaco',
    estilo: 'Criativo',
    cor: 'Terracota',
    tamanhos: ['M', 'G'],
    preco: 289,
    status: 'PUBLICADO',
  },
  {
    id: 'AN-1824',
    fotoUrl: null,
    nome: 'Vestido Longo Preto',
    codigo: 'AN-1824',
    peca: 'Vestido',
    estilo: 'Dramático',
    cor: 'Preto',
    tamanhos: ['P', 'M'],
    preco: 349,
    status: 'PAUSADO',
  },
  {
    id: 'AN-1819',
    fotoUrl: null,
    nome: 'Sapatilha Preta',
    codigo: 'AN-1819',
    peca: 'Sapato',
    estilo: 'Refinado',
    cor: 'Preto',
    tamanhos: ['35', '36', '37', '38', '39'],
    preco: 179,
    status: 'PUBLICADO',
  },
  {
    id: 'AN-1814',
    fotoUrl: null,
    nome: 'Camiseta Lisa Off-white',
    codigo: 'AN-1814',
    peca: 'Camiseta',
    estilo: 'Casual',
    cor: 'Off-white',
    tamanhos: ['P', 'M', 'G'],
    preco: 89.9,
    status: 'RASCUNHO',
  },
];
